apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-worker
spec:
  selector:
    matchLabels:
      app: nfd-worker
  template:
    metadata:
      labels:
        app: nfd-worker
    spec:
      serviceAccount: nfd-worker
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nfd-worker
          image: quay.io/kubernetes_incubator/node-feature-discovery:master
          imagePullPolicy: Always
          command:
            - "nfd-worker"
          args:
            - "--server=nfd-master:8080"
          ports:
            - name: metrics
              containerPort: 8081
