apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd
spec:
  selector:
    matchLabels:
      app: nfd
  template:
    metadata:
      labels:
        app: nfd
    spec:
      serviceAccount: nfd-master
      enableServiceLinks: false
      tolerations: []
      containers:
      - name: nfd-master
        image: quay.io/kubernetes_incubator/node-feature-discovery:master
        imagePullPolicy: Always
        command:
        - "nfd-master"
      - name: nfd-worker
        image: quay.io/kubernetes_incubator/node-feature-discovery:master
        imagePullPolicy: Always
        command:
        - "nfd-worker"
        args: []
